export const DEFAULT_CONTENT = {
  siteName: 'Jodie Peltier',
  tagline: 'Préparation mentale',
  heroTitle: 'Le mental au service de ta réussite !',
  heroSubtitle: 'Accompagnement en préparation mentale, en individuel et en collectif, pense pour vos besoins.',
  heroImage: '',
  heroQuote: '',
  heroStyle: 'fullwidth',
  announcement: '',
  navHomeLabel: 'Accueil',
  navWhatLabel: "C'est quoi ?",
  navEthicsLabel: 'Éthique',
  navAboutLabel: 'Qui suis-je',
  navServicesLabel: 'Services',
  navContactLabel: 'Contact',
  aboutShort: '',
  aboutLong: '',
  aboutPhoto: '',
  aboutTargets: [],
  formations: [],
  memoires: [],
  ethicsTitle: 'Éthique et déontologie',
  ethicsText: '',
  ethicsImage: '',
  ethicsSchema: '',
  ethicsPrinciples: [
    { title: 'Confidentialité', description: '' },
    { title: 'Bienveillance', description: '' },
    { title: 'Consentement', description: '' },
    { title: 'Respect', description: '' },
    { title: 'Transparence', description: '' },
  ],
  whatIsTitle: 'La préparation mentale',
  whatIsText: '',
  whatDistinctionTitle: '',
  whatDistinctionText: '',
  whatSections: [],
  forWhomTitle: 'Pour qui ?',
  forWhomItems: [],
  stats: { clients: 150, years: 5, satisfaction: 98, specialties: 3 },
  testimonials: [],
  contactEmail: '',
  contactPhone: '',
  contactLocation: '',
  socialLinks: {},
  googleApiKey: '',
  googlePlaceId: '',
  logo: '',
  logoFooter: '',
  favicon: '',
  legalMentions: '',
  legalCookies: '',
  legalPrivacy: '',
  legalTerms: '',
  faq: [],
  resources: [],
};

export const DEFAULT_SERVICES = [];
export const DEFAULT_BOOKINGS = [];
export const DEFAULT_APP_SETTINGS = {
  emailSubjectConfirm: 'Confirmation de votre séance — {service}',
  emailSubjectCancel: 'Annulation de votre séance — {service}',
  emailSubjectDelete: 'Votre réservation — {service}',
  emailTemplateConfirm: '',
  emailTemplateCancel: '',
  emailTemplateDelete: '',
  notifSubject: '🔔 Nouvelle demande — {service}',
  notifTemplate: '',
  testEmail: '',
};

export const DEFAULT_GOOGLE_REVIEWS = [
  { author_name: 'Claire M.', rating: 5, text: "Un accompagnement bienveillant et très professionnel. Jodie a su m'aider à surmonter le stress des compétitions avec des outils concrets et efficaces.", profile_photo_url: '', relative_time_description: 'il y a 2 semaines' },
  { author_name: 'Lucas B.', rating: 5, text: "J'ai découvert la préparation mentale grâce à Jodie. En quelques séances j'ai gagné une vraie clarté sur mes objectifs. Je recommande vivement.", profile_photo_url: '', relative_time_description: 'il y a 1 mois' },
  { author_name: 'Sarah D.', rating: 5, text: "Jodie est à l'écoute, empathique et très compétente. Les exercices proposés m'ont vraiment aidée à gérer mon anxiété avant les examens.", profile_photo_url: '', relative_time_description: 'il y a 2 mois' },
  { author_name: 'Antoine R.', rating: 5, text: "Très bonne expérience. Les séances sont structurées, adaptées à mes besoins et les progrès sont visibles rapidement. Merci Jodie !", profile_photo_url: '', relative_time_description: 'il y a 3 mois' },
  { author_name: 'Émilie T.', rating: 4, text: "Accompagnement sérieux et personnalisé. J'apprécie la rigueur scientifique de la démarche, tout en restant dans un cadre chaleureux.", profile_photo_url: '', relative_time_description: 'il y a 4 mois' },
];
